# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-2.0',
                'doc_host': 'https://goodCodeForGood.github.io',
                'git_url': 'https://github.com/goodCodeForGood/nbdev-2.0',
                'lib_path': 'nbdev_2.0'},
  'syms': {'nbdev_2.0.core': {'nbdev_2.0.core.foo': ('core.html#foo', 'nbdev_2.0/core.py')}}}
